<?php
/**
 * Right-to-left stylesheets: generated, fresh, and registered.
 *
 * Every shipped stylesheet has an rtlcss-generated sibling (assets/css/
 * X-rtl.css, committed, produced by bin/build-rtl.sh) that WordPress swaps
 * in on RTL locales because the handle is registered with
 * wp_style_add_data( $handle, 'rtl', 'replace' ). Three things can rot:
 *
 *   1. a stylesheet is edited and the sibling is not regenerated — caught
 *      by the SHA-1 stamp the generator writes on the sibling's first line;
 *   2. a new stylesheet ships without a sibling;
 *   3. a stylesheet is enqueued somewhere without the registration.
 *
 * Pure file inspection; no WordPress.
 *
 * @package PostRuntimeEngine\Tests\Unit
 */

namespace PRE\Tests\Unit;

class RtlStylesheetsTest extends UnitTestCase {

	private function sources() {
		$all = glob( PRE_TEST_PLUGIN_DIR . 'assets/css/*.css' );
		return array_values( array_filter( $all, static function ( $f ) {
			return substr( $f, -8 ) !== '-rtl.css';
		} ) );
	}

	public function test_every_stylesheet_has_a_generated_sibling_built_from_its_current_content() {
		$sources = $this->sources();
		$this->assertNotEmpty( $sources );
		foreach ( $sources as $src ) {
			$rtl = substr( $src, 0, -4 ) . '-rtl.css';
			$this->assertFileExists( $rtl, basename( $src ) . ' has no -rtl.css sibling — run bin/build-rtl.sh' );
			$first = strtok( (string) file_get_contents( $rtl ), "\n" );
			$this->assertSame(
				1,
				preg_match( '/^\/\* rtl: generated by bin\/build-rtl\.sh from ' . preg_quote( basename( $src ), '/' ) . ' \(sha1 ([0-9a-f]{40})\)/', (string) $first, $m ),
				basename( $rtl ) . ' does not start with the generator stamp'
			);
			$this->assertSame(
				sha1_file( $src ),
				$m[1],
				basename( $src ) . ' changed since its -rtl.css was generated — run bin/build-rtl.sh'
			);
			$this->assertGreaterThan( 100, filesize( $rtl ), basename( $rtl ) . ' is suspiciously small' );
		}
	}

	public function test_every_enqueue_of_a_shipped_stylesheet_registers_the_rtl_sibling() {
		$files   = glob( PRE_TEST_PLUGIN_DIR . 'includes/*/*.php' );
		$files[] = PRE_TEST_PLUGIN_DIR . 'post-runtime-engine.php';
		$seen    = 0;
		foreach ( $files as $file ) {
			$src = (string) file_get_contents( $file );
			if ( preg_match_all( '/wp_(?:enqueue|register)_style\(\s*\'([a-z0-9-]+)\'\s*,[^;]*?assets\/css\/([a-z0-9-]+)\.css\'/s', $src, $m, PREG_OFFSET_CAPTURE | PREG_SET_ORDER ) ) {
				foreach ( $m as $hit ) {
					$seen++;
					$handle = $hit[1][0];
					$after  = substr( $src, $hit[0][1], 900 );
					$this->assertSame(
						1,
						preg_match( '/wp_style_add_data\(\s*\'' . preg_quote( $handle, '/' ) . '\'\s*,\s*\'rtl\'\s*,\s*\'replace\'\s*\)/', $after ),
						basename( $file ) . ": '{$handle}' (assets/css/{$hit[2][0]}.css) is enqueued without wp_style_add_data( …, 'rtl', 'replace' )"
					);
				}
			}
		}
		$this->assertGreaterThanOrEqual( 7, $seen, 'expected to find the stylesheet enqueue sites' );
	}
}
